server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: DIMETHYLTRYPTAMINE
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: rskmfinance
  jpa:
    open-in-view: false
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    password: Dimethyltryptamine
    username: developer.rskmicrofinance@outlook.com
    port: 587
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
    test-connection: true
