CREATE TABLE PRODUCTS (
ID NUMBER(10) NOT NULL,
NAME VARCHAR2(255),
TITLE VARCHAR2(255),
DESCRIPTION CLOB,
AMOUNT NUMBER(6),
TYPE VARCHAR2(255),
MEDIA BLOB,
UNIQUE(ID)
);

CREATE SEQUENCE  PRODUCTS_SEQ  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE;
