CREATE TABLE REQUESTS (
    ID NUMBER(10) NOT NULL,
    CUSTOMER_NAME VARCHAR2(255),
    CUSTOMER_NUMBER NUMBER(6),
    PRODUCT_ID NUMBER(10),
    REQUESTS_STATUS VARCHAR2(255),
    ACCOUNT_OFFICER_NAME VARCHAR2(255),
    ACCOUNT_OFFICER_USER_ID VARCHAR2(255),
    CREATED_DATE_TIME DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(255),
    MODIFIED_DATE_TIME DATE DEFAULT SYSDATE,
    MODIFIED_BY VARCHAR2(255),
    ACTION VARCHAR2(255),
    APPLY_REASON CLOB, 
    PAYMENT_OPTION NUMBER(10,0), 
    POA CLOB,
    POA_NAME VARCHAR2(255 BYTE), 
    POI CLOB, 
    POI_NAME VARCHAR2(255 BYTE), 
    SIGNATURE CLOB,
    SIGNATURE_NAME VARCHAR2(255 BYTE)
);

CREATE SEQUENCE  REQUESTS_SEQ  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE;

ALTER TABLE REQUESTS ADD APPLY_REASON CLOB;
ALTER TABLE REQUESTS ADD PAYMENT_OPTION NUMBER(10);
ALTER TABLE REQUESTS ADD POA BLOB;
ALTER TABLE REQUESTS ADD POI BLOB;
ALTER TABLE REQUESTS ADD SIGNATURE BLOB;
ALTER TABLE REQUESTS ADD POA_NAME VARCHAR2(255);
ALTER TABLE REQUESTS ADD POI_NAME VARCHAR2(255);
ALTER TABLE REQUESTS ADD SIGNATURE_NAME VARCHAR2(255);

