SELECT * FROM USERS;

DELETE FROM USERS WHERE USERNAME = 'xrannan@outlook.com';
DELETE FROM USERS WHERE ID = 10;

UPDATE USERS SET ACTIVE = 0 WHERE USERNAME = 'xrannan@outlook.com';

DELETE FROM USERS WHERE phone = 0;