SELECT * FROM USERS;

SELECT ACTIVE, ROLES FROM USERS;

DELETE FROM USERS WHERE USERNAME = 'rxyloto@gmail.com';
DELETE FROM USERS WHERE ID = 10;

UPDATE USERS SET ACTIVE = 0 WHERE USERNAME = 'xrannan@outlook.com';

DELETE FROM USERS WHERE USERNAME = 'admin';
DELETE FROM USERS WHERE USERNAME = 'xrannan@outlook.com';
DELETE FROM USERS WHERE phone = 0;

UPDATE USERS SET USERNAME = 'xrannan' WHERE USERNAME = 'admin';
UPDATE USERS SET ROLES = 'ROLE_ADMIN' WHERE USERNAME = 'admin';

DELETE FROM PRODUCTS;
SELECT * FROM PRODUCTS;

SELECT * FROM REQUESTS;

DESC REQUESTS;
DESC PRODUCTS;

ALTER TABLE REQUESTS RENAME COLUMN MODFIFIED_BY TO MODIFIED_BY;

DELETE FROM REQUESTS WHERE CUSTOMER_NAME = 'Rannan Chaikin';
DELETE FROM REQUESTS WHERE ID = 16;

UPDATE REQUESTS SET PRODUCT_ID = 35 WHERE ID = 8;
UPDATE REQUESTS SET CREATED_DATE_TIME = '29-DEC-20' WHERE ID = 16;

UPDATE REQUESTS SET ACTION = 'PROGRESS' WHERE ACTION = 'APPLIED';

29-DEC-20

ALTER USER rskmfinance IDENTIFIED BY DIMETHYLTRYPTAMINE;

DROP TABLE REQUESTS;

DELETE FROM REQUESTS;


















