DROP TABLE USERS;

CREATE TABLE USERS (
ID NUMBER(10) NOT NULL,
USERNAME VARCHAR2(255),
PASSWORD VARCHAR2(255),
FIRST_NAME VARCHAR2(255),
LAST_NAME VARCHAR2(255),
NIC VARCHAR2(255),
PHONE NUMBER(38),
ADDRESS VARCHAR2(255),
DATE_OF_BIRTH DATE,
EMAIL VARCHAR2(255),
ROLES VARCHAR2(50),
ACTIVE VARCHAR2(10),
TOKEN varchar(25),
UNIQUE(ID)
);

CREATE SEQUENCE  USERS_SEQ  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE;

DELETE FROM USERS;

Insert into USERS (ID,USERNAME,PASSWORD,PHONE,EMAIL,ROLES,ACTIVE,TOKEN) values (1,'shakya','moksha',0,'xrannan@outlook.com','ROLE_USER','TRUE','');
Insert into USERS (ID,USERNAME,PASSWORD,PHONE,EMAIL,ROLES,ACTIVE,TOKEN) values (2,'judizia','psyko',0,'12merlino@gmail.com','ROLE_USER','false','');
Insert into USERS (ID,USERNAME,PASSWORD,PHONE,EMAIL,ROLES,ACTIVE,TOKEN) values (3,'admin','password',0,'developer.rskmicrofinance@outlook.com','ROLE_ADMIN','TRUE','');

INSERT INTO USERS(ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,NIC,PHONE,ADDRESS,DATE_OF_BIRTH,EMAIL,ROLES,ACTIVE,TOKEN) 
VALUES (4,'rxyloto','RXYLOTO','RANNAN','CHAIKIN','S0210968261345',59238680,'56 RAILWAY ROAD, HIGHLANDS PHOENIX',(TO_DATE('10/02/1999', 'dd/mm/yyyy')),'rxyloto@gmail.com','ROLE_ADMIN','TRUE','');

INSERT INTO USERS(ID,USERNAME,PASSWORD,FIRST_NAME,LAST_NAME,NIC,PHONE,ADDRESS,DATE_OF_BIRTH,EMAIL,ROLES,ACTIVE,TOKEN) 
VALUES (0,'admin','password','Admin','Admin','S00000000000',59238680,'Address',(TO_DATE('10/02/1996', 'dd/mm/yyyy')),'developer.rskmicrofinance@outlook.com','ROLE_ADMIN','TRUE','');

ALTER TABLE USERS ADD POA BLOB;
ALTER TABLE USERS ADD POI BLOB;
ALTER TABLE USERS ADD POA_NAME VARCHAR2(255);
ALTER TABLE USERS ADD POI_NAME VARCHAR2(255);

SELECT * FROM USERS;



























































